name: Android Build CI

on:
  push:
    branches: [ master ]
    paths-ignore: [ '**.md', '**.MD' ]
  pull_request:
    branches: [ master ]
    paths-ignore: [ '**.md', '**.MD' ]
  workflow_dispatch:

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Spotless check
        run: ./gradlew spotlessCheck

      - name: Build debug APK
        run: ./gradlew assembleDebug --warning-mode all --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@master
        with:
          name: app-debug
          path: androidApp/build/outputs/apk/debug/androidApp-debug.apk
